apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: updated
        image: nginx:1.21
        args:
        - start-server
        command:
        - /bin/sh
        - -c
        ports:
        - containerPort: 80
        env:
        - name: ENABLE_LOGS
          value: 'true'
