metadata:
  name: "guestbook-ui"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "guestbook-ui"
    spec:
      containers:
      - name: "baramundi"
        image: "gcr.io/heptio-images/ks-guestbook-demo:0.2"
        ports:
        - containerPort: 80
  xyz: "1"
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "guestbook-ui"
  replicas: 1
