metadata:
  name: "guestbook-ui"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "guestbook-ui"
    spec:
      containers:
      - image: "abc"
        name: "baramundi"
        ports:
        - containerPort: 80
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "guestbook-ui"
  replicas: 1
