metadata:
  name: "guestbook-ui"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "guestbook-ui"
    spec:
      containers:
      - name: "baramundi"
        image: "abc"
        ports:
        - containerPort: 80
  abc:
    a[0]:
      bla: "asdf"
  replicas: 5
  xyz: "2"
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "guestbook-ui"
