a:
  b:
    c:
      d: "sadf"
apiVersion: "v1"
items:
- metadata:
    name: "quote-test-deployment"
    annotations:
      special.chars/config-map-ref: "key: value"
      null.as.string/optional-field: "null"
      octal.as.string/permission-code: "0755"
      escaped.chars/json-snippet: "{\"key\": \"value with a \\\"quote\\\" and a newline\\\
        n\"}"
      booleans.as.string/is-enabled: "true"
      numbers.as.string/version-id: "12345"
  apiVersion: "apps/v1"
  kind: "Deployment"
  spec:
    template:
      metadata:
        labels:
          app: "quote-test"
      spec:
        containers:
        - args:
          - "8080"
          - "off"
          - "special: arg"
          image: "nginx:1.25.2"
          name: "nginx"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: "ENABLE_FEATURE_X"
            value: "false"
          - name: "MAX_RETRIES"
            value: "5"
          - name: "POD_NAME"
            value: "quote-test-pod"
        initContainers:
        - image: "busybox:1.36"
          name: "setup"
          env:
          - name: "ENABLE_FEATURE_X"
            value: "false"
          - name: "MAX_RETRIES"
            value: "5"
          - name: "POD_NAME"
            value: "quote-test-pod"
    replicas: 1
    selector:
      matchLabels:
        app: "quote-test"
- metadata:
    name: "quote-test-config"
  apiVersion: "v1"
  data:
    app.properties: "# This is a literal block scalar.\n# It must not be converted\
      \ to a giant quoted string.\nservice.url=http://example.com\n"
    explicit-integer: 123
    welcome-message.txt: "This is a folded block scalar. Newlines are converted to\
      \ spaces.\n"
    explicit-string: "123.45"
    multi-line-quoted-string: "This is the first line of a long string that continues\
      \ on the second line. The backslash at the end of the first line preserves the\
      \ line break."
  kind: "ConfigMap"
- metadata:
    name: "special-char-secret-test"
  apiVersion: "v1"
  kind: "Secret"
  type: "Opaque"
  stringData:
    windows-path: "C:\\Users\\Test"
    is-a-dash: "-"
    is-just-a-space: " "
    is-a-colon: ":"
- metadata:
    name: "quote-test-service"
  apiVersion: "v1"
  kind: "Service"
  spec:
    selector:
      app: "quote-test"
    ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
kind: "List"
bla: "bla"
