apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quote-test-deployment
    annotations:
      booleans.as.string/is-enabled: 'true'
      numbers.as.string/version-id: '12345'
      octal.as.string/permission-code: '0755'
      null.as.string/optional-field: 'null'
      special.chars/config-map-ref: 'key: value'
      escaped.chars/json-snippet: '{"key": "value with a \"quote\" and a newline\n"}'
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: quote-test
    template:
      metadata:
        labels:
          app: quote-test
      spec:
        initContainers:
        - name: setup
          image: busybox:1.36
          env: &id001
          - name: ENABLE_FEATURE_X
            value: 'false'
          - name: MAX_RETRIES
            value: '5'
          - name: POD_NAME
            value: quote-test-pod
        containers:
        - name: nginx
          image: nginx:1.25.2
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          env: *id001
          args:
          - '8080'
          - 'off'
          - 'special: arg'
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: quote-test-config
  data:
    app.properties: |
      # This is a literal block scalar.
      # It must not be converted to a giant quoted string.
      service.url=http://example.com
    welcome-message.txt: |
      This is a folded block scalar. Newlines are converted to spaces.
    multi-line-quoted-string: This is the first line of a long string that continues on the second line. The backslash at the end of the first line preserves the line break.
    explicit-string: '123.45'
    explicit-integer: 123
- apiVersion: v1
  kind: Secret
  metadata:
    name: special-char-secret-test
  type: Opaque
  stringData:
    windows-path: C:\Users\Test
    is-a-dash: '-'
    is-a-colon: ':'
    is-just-a-space: ' '
- apiVersion: v1
  kind: Service
  metadata:
    name: quote-test-service
  spec:
    selector:
      app: quote-test
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
bla: bla
a:
  b:
    c:
      d: sadf
