apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-nginx-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://localhost:8080;
      }
      location /health {
        return 200 'OK';
      }
    }
