apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-app-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.env }}
  LOG_LEVEL: "info"
  REDIS_PORT: "{{ .Values.redis.port }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
